### ISSUE TITLE
Button icons not present

### ISSUE THREAD

**Issue by LewisSpring** [costas-basdekis/MarlinGcodeDocumentation#10]
- OP 0.15.1
- Python 3.7.3
- Plugin 0.11.0
- Terminal Messaging 0.1.0

![image](https://user-images.githubusercontent.com/40576482/101660644-4df22e80-3a3f-11eb-8faa-08ea0aa6dd50.png)

Let ne know if you need anymore information!

**Comment by costas-basdekis** [comment]
Hm, very interesting! I'm not adding a new font, so it could be a problem of a font being blocked.

I'll have a look, but can you see if there are any errors in the console/network tab, around fonts?

Thanks for the heads up @thelewiss1 !

**Comment by LewisSpring** [comment]
> console/network

![image](https://user-images.githubusercontent.com/40576482/101663700-efc74a80-3a42-11eb-8349-0d8e4d79f761.png)
![image](https://user-images.githubusercontent.com/40576482/101663902-20a77f80-3a43-11eb-95a5-15bb923683b7.png)

I'm also getting lots of these errors right after screencapping the console tab: 
![image](https://user-images.githubusercontent.com/40576482/101664014-46348900-3a43-11eb-981e-3aa2eb409839.png)
and the terminal kept going blank/using "basic" mode. Not sure what that's about, but the icon issue has been happening before this.

**Comment by costas-basdekis** [comment]
Hm, no issues there. I'll try to have a look

**Comment by LewisSpring** [comment]
> Hm, no issues there. I'll try to have a look

Hello! Any updates? The issue still persists.

**Comment by costas-basdekis** [comment]
Hi @thelewiss1 sorry for the delay.

I've had a look in different installations and I couldn't find anything.

2 things to try:
* If you check your network tab, do you see successful entries for `fontawesome-webfont.woff2`?
* If you inspect the missing icon (Ctrl+Shift+C on Windows/Linux and then click on the green square icon), what do you see as the entry for font? Is it `normal normal normal 14px/1 FontAwesome`? If you change it to `14px FontAwesome` does that fix it?

If neither of these work, I'm not sure how to diagnose. Perhaps if you gave me access to your instance?

**Comment by LewisSpring** [comment]
> Hi @thelewiss1 sorry for the delay.
> 
> I've had a look in different installations and I couldn't find anything.
> 
> 2 things to try:
> 
> * If you check your network tab, do you see successful entries for `fontawesome-webfont.woff2`?
> * If you inspect the missing icon (Ctrl+Shift+C on Windows/Linux and then click on the green square icon), what do you see as the entry for font? Is it `normal normal normal 14px/1 FontAwesome`? If you change it to `14px FontAwesome` does that fix it?
> 
> If neither of these work, I'm not sure how to diagnose. Perhaps if you gave me access to your instance?

I don't see any network activity for fontawesome*.
This is what I see for your second point:
![image](https://user-images.githubusercontent.com/40576482/104850881-9841b780-58e9-11eb-9001-4786973af5fe.png)

I don't have any way for you to access my instance unfortunately. Is there a way i can purge the install of the plugin? I have since installed Octopi on a new Pi and restored from the configuration backup. - the issue still remains

**Comment by costas-basdekis** [comment]
It would be **very weird** if there is no FontAwesome since it's included with OctoPrint (unless I'm really missing something).

If you click on the `::after` element, you should see `font` in `Styles` sub-tab and replace with `14px FontAwesome`

![image](https://user-images.githubusercontent.com/2470905/104852396-c4156b00-58f2-11eb-9edf-9a3d3107fad6.png)

BTW the missing icon is something added by the plugin, if it annoys you that's missing you can disable it by going in the plugin settings and unchecking `Add links to sent commands in terminal to get documentation`

You can give access to your instance by either using [Localtunnel](http://localtunnel.github.io/www/) or a remote access OctoPrint plugin

**Comment by costas-basdekis** [comment]
Actually, one last thing you can try: replace `font` value with `14px "Font Awesome 5 Brands"`

**Comment by LewisSpring** [comment]
I've found what you meant. My mistake.
I've tried 
"normal normal normal 14px "Font Awesome 5 Brands""
"14px "Font Awesome 5 Brands" 
"normal normal normal 14px FontAwesome"
"14px FontAwesome"

to no change.

**Comment by costas-basdekis** [comment]
I really not sure how else to help here.

I've just run a fresh install with only MGCD and TM, and it works fine.

I just noticed. Are you saying you have version 0.15.1 of OctoPrint? My version is 1.4.2, and the latest one is 1.5.2.

So if you have such an old installation, I'm afraid there is not that much I can do

**Comment by LewisSpring** [comment]
> I really not sure how else to help here.
> 
> I've just run a fresh install with only MGCD and TM, and it works fine.
> 
> I just noticed. Are you saying you have version 0.15.1 of OctoPrint? My version is 1.4.2, and the latest one is 1.5.2.
> So if you have such an old installation, I'm afraid there is not that much I can do

I'm using 1.5.2 of Octoprint. That could have been a typing mistake. I'm printing at the moment, but i will try to remove the plugin again. Is there anything I can delete in files to ensure everything is uninstalled before reinstalling?

**Comment by costas-basdekis** [comment]
Ok, haha, 0.15.2 would be difficult to install!

There doesn't seem anything wrong with this plugin, so uninstalling and reinstalling just MGD would probably make no difference.

The problem seems to be with not being able to access a font provided by OP. Unless you use something like LocalTunnel it'd be hard to debug it.

If you're not using this feature best thing would be to disable it.

**Comment by LewisSpring** [comment]
> Ok, haha, 0.15.2 would be difficult to install!
> 
> There doesn't seem anything wrong with this plugin, so uninstalling and reinstalling just MGD would probably make no difference.
> 
> The problem seems to be with not being able to access a font provided by OP. Unless you use something like LocalTunnel it'd be hard to debug it.
> 
> If you're not using this feature best thing would be to disable it.

I don't particularly use the feature, so i'll turn it off. I'll just copy and paste the command if I need.

Thanks!

**Comment by costas-basdekis** [comment]
Apologies for not figuring a solution.

If you ever figure it out let me know.
