### ISSUE TITLE
Feature request: Add configuration for the documentation repository selections

### ISSUE THREAD

**Issue by Sembazuru** [costas-basdekis/MarlinGcodeDocumentation#12]
Having the check boxes for which documentation repositories are used on the main interface is getting really cluttered. I use consolidated tabs and all the selections don't fit so I can't see all of them:
<img width="349" alt="2021-03-13 16_27_41-10% 06_58 (printing)" src="https://user-images.githubusercontent.com/4469286/111044860-179ac580-8419-11eb-8973-48ac30202548.png">

It would be nice to move these to a configuration interface to reduce the clutter. Maybe have a quick link to the configuration page (like a pencil icon next to the expand and collapse buttons) instead of always having to find it in the OctoPrint configuration window.

**Comment by costas-basdekis** [comment]
Thanks for the suggestion @Sembazuru !

These settings are already present on the settings tab, do you want to also have an option to not show those checkboxes in the console section?

**Comment by Sembazuru** [comment]
Silly me. I didn't even look for the configuration and had forgotten it was there. This repository's README.md states "There is no configuration currently." in the configuration section and I was basing at least part of the request on that... https://github.com/costas-basdekis/MarlinGcodeDocumentation#configuration

Yes, I'd like a switch to not show those checkboxes in the console section. This would reduce some of my self-imposed clutter.

**Comment by costas-basdekis** [comment]
Now there is an option to hide them from there
