### ISSUE TITLE
Klipper documentation doesn't seem to be working

### ISSUE THREAD

**Issue by gcarvalho** [costas-basdekis/MarlinGcodeDocumentation#14]
I'm starting to use klipper for the first time and the plugin doesn't seem to recognise any of the commands.
I tried switching on plugin logging but the log shows nothing unusual. I also don't seem to find any errors in the inspect console.
Anything I should look into?

**Comment by costas-basdekis** [comment]
Thanks for reporting this @gcarvalho!

Can you post some examples of commands that are not recognised? I though I was parsing them properly.

I should probably add some tests

**Comment by gcarvalho** [comment]
Hey, apologies, I logged off github and only noticed now.
All of them, at least on my setup. PROBE_CALIBRATE, as an example.

**Comment by degtyarev708** [comment]
Standard gcode shows up just fine, however none of klippers "extended gcode" is recognized https://www.klipper3d.org/G-Codes.html

**Comment by pandel** [comment]
+1
It would be very nice if this could be fixed :-)

**Comment by pandel** [comment]
I think, at least here is something going wrong: https://github.com/costas-basdekis/MarlinGcodeDocumentation/blob/b0eabaf3beb513e27a21c39f6fa03a38c1770943/octoprint_marlingcodedocumentation/parser/parsers/klipper.py#L118

`sibling` is a NavigableString or Tag, I think. If I change the code from line 118 to this

```
        next_text = next(filter(None, (
            str(sibling).replace('\n', '').strip().strip(':').strip()
            for sibling in list_item.previous_siblings
            if isinstance(sibling, object)
        )), '')
```

then, at least, next_text is not empty. But I don't have enough time to dig into this any further...

**Comment by costas-basdekis** [comment]
Hi, thank you everyone for these comments and suggestions!

I have now updated how I parse Klipper documentation.

I'll soon [release 0.14.0](https://github.com/costas-basdekis/MarlinGcodeDocumentation/releases/tag/v0.14.0)

In the future, don't be afraid to create a PR if you think you can improve the parsing.
