### ISSUE TITLE
"Include from" causes unsightly overlap

### ISSUE THREAD

**Issue by JesseHawkins-zz** [costas-basdekis/MarlinGcodeDocumentation#15]
I suggest that these changes be made to stop this:

https://i.imgur.com/PHy8UU3.png

Change from:

/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:81:        Include from Marlin
/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:85:        Include from RepRap
/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:89:        Include from Klipper

Change to:

/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:81:        Marlin
/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:85:        RepRap
/octoprint_marlingcodedocumentation/templates/marlingcodedocumentation.jinja2:89:        Klipper

End result:

https://i.imgur.com/DvBgBPH.png

While writing this, it occured to me that this setting might make more sense to bury in a settings page with other plugins. Perhaps some users with multiple printers might need to switch between documentation on the fly, but then just have an option to show/hide these on the console tab.

**Comment by costas-basdekis** [comment]
Thanks for the suggestion @JesseHawkins 

Do you have a PR you can submit?

Otherwise, I'll try to get it in soon

**Comment by JesseHawkins-zz** [comment]
Submitted, however I am using GitHub for the first time in years. I have no clue if I did it correctly.  https://github.com/costas-basdekis/MarlinGcodeDocumentation/pull/16

**Comment by costas-basdekis** [comment]
That's great, thanks! Welcome to GitHub

**Comment by costas-basdekis** [comment]
It's released, and should be available for update soon

https://github.com/costas-basdekis/MarlinGcodeDocumentation/releases/tag/v0.15.0

Do let me know if you have any ideas or suggestions, and thanks for the PR!
