### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by NekkoArms** [costas-basdekis/MarlinGcodeDocumentation#17]
I am hoping for an option to turn off the "Are you sure you want to replace the current command?" box

**Comment by costas-basdekis** [comment]
Thanks for the suggestion @NekkoArms! I'll actually consider completely removing it. It does sound unnecessary.

If you can submit a PR, please do, otherwise I'll try to do it myself soon.

**Comment by costas-basdekis** [comment]
@NekkoArms I've removed the prompt (and added a non-intrusive "undo" button).

It should be on OP soon

**Comment by NekkoArms** [comment]
PR?

**Comment by costas-basdekis** [comment]
Pull request, meaning you've made some changes in your copy of this code, and have asked me to include those changes in the main repo

For example see https://github.com/costas-basdekis/MarlinGcodeDocumentation/pull/16
