### ISSUE TITLE
Fails to Work with MultiLine Terminal

### ISSUE THREAD

**Issue by ghost** [costas-basdekis/MarlinGcodeDocumentation#2]
If using Multi Line Terminal (0.1.3) plugin, this fine plugin fails to show GCode help.
Not sure what you can do to fix that tho as two or more lines might garble up the page.
Maybe add a ? to perform the actual info - I could live with that.
Thought about this some more - only offer help on last line!

**Comment by costas-basdekis** [comment]
Thanks for that, I'll have a look and see how I can support MLT 👍 

Ideally it will show help for the line at the cursor position, and maybe all lines

**Comment by costas-basdekis** [comment]
I have pushed a new version that should support MLT.

Let me know if that works fine @CmdrCody51

**Comment by ghost** [comment]
> I have pushed a new version that should support MLT.
> 
> Let me know if that works fine @CmdrCody51

Well - I would say PERFECT!
Thank you!
