### ISSUE TITLE
Problem with documentation for command M121

### ISSUE THREAD

**Issue by EasyG0ing1** [costas-basdekis/MarlinGcodeDocumentation#22]
For command M120, the documentation says:

```
Enable endstops and keep them enabled when not homing
```

For command M121, the documentation says:
```
Disable endstops and keep them enabled when not homing
```

Notice that both commands say that the endstops will remain ENABLED when not homing.  I *THINK* that for M121, it is supposed to read ```keep them disabled when not homing```?

**Comment by costas-basdekis** [comment]
Hi @EasyG0ing1, thank you for the report!

The documentation comes from the firmwares' documenation, and I don't actually edit them myself.

For `M121`, it looks like the [primary source](https://marlinfw.org/docs/gcode/M121) has that phrase, that might be a mistake. You can either contact Marlin to fix it, or click on the "Edit page" button to submit a PR to fix that.
