### ISSUE TITLE
Terminal Font Remains Styled After Uninstall

### ISSUE THREAD

**Issue by shatteredsite** [costas-basdekis/MarlinGcodeDocumentation#3]
When uninstalling, the terminal GCODE is still displayed in the style (css) given to it by MarlinGcodeDocumentation. This makes reading on a dark theme extremely difficult. I have both uninstalled and re-installed Themeify to try and fix the issue, with no luck.

**Comment by costas-basdekis** [comment]
Thanks for the report @shatteredsite 

Can you post a screenshot? The styling I'm using for the documentation is strictly targeted at the portion of the documentation, so I can't imagine how would it affect anything else.
