### ISSUE TITLE
Plugin still says it's out of date despite being the latest version

### ISSUE THREAD

**Issue by NovaViper** [costas-basdekis/MarlinGcodeDocumentation#7]
Hi, I just updated the plugin from version 0.9.2 to 0.10.0 but Octoprint still says that the plugin isn't update to date. Using Octoprint version 1.4.2.

![image](https://user-images.githubusercontent.com/7191115/94821539-4a9b5080-03c7-11eb-9a4a-11142f9f2d0d.png)

**Comment by costas-basdekis** [comment]
Hi, thanks for this.

I'm not sure if this is an issue with this plugin specifically, or an issue with how OctoPrint handles updates.

I'd appreciate if @jneilliii could help here, since I followed the cookie cutter for this plugin.

**Comment by martinglass** [comment]
Nothing to do with this plugin specifically. It's taken a while for the update to filter through to the Octoprint Plugin database and then be pushed to users. I think that it's all okay now, although if you've updated already you might still see an update warning, saying that the latest version is now available,  Strange!

**Comment by fnsign** [comment]
I think there is a typo or kind of version mismatch. Octoprints plugin site say v0.9.2., the release is named v0.10.0 and the master is 0.10.2? This mismatch of versions causes reboot and access problems to the WebUI on my RPi. For the time beeing I have uninstalled the plugin to regain access to Octoprint again.

**Comment by costas-basdekis** [comment]
You have a keen eye @fnsign, thank you, and apologies for the inconvenience.

I've pushed a new release v0.10.3 @NovaViper

**Comment by jneilliii** [comment]
Yeah, versioning of the plugin is entirely controlled by your github repo here. All you have to do is make sure that when you create your release in github that the setup.py file has the matching version number when you create it, because that's how it will download.

**Comment by NovaViper** [comment]
@costas-basdekis That fixed it, thanks!
