### ISSUE TITLE
Klipper Support

### ISSUE THREAD

**Issue by DroneMang** [costas-basdekis/MarlinGcodeDocumentation#9]
Hi!

Let me first say this is very useful as it is.  I use Klipper and many of the commands are not recognized, I was just wondering if someday there could be support for Klipper.  Thanks!

DroneMang

**Comment by costas-basdekis** [comment]
Thanks for the suggestion @DroneMang.

I though most Klipper commands would be included in the RepRap documentation. Do you know if there is Klipper documentation for those commands somewhere?

**Comment by cmfrolick** [comment]
@costas-basdekis 

Klipper G-Code documentation can be found at https://www.klipper3d.org/G-Codes.html

Klipper supports a subset of the RepRap G-Code and has it's own extended command set for managing the firmeware and printer control.

**Comment by costas-basdekis** [comment]
I've added support for Klipper now and it'll be available on the next release @cmfrolick

**Comment by DroneMang** [comment]
Awesome!

**Comment by costas-basdekis** [comment]
It should be live now
